### ISSUE TITLE
Update repo summary URL

### ISSUE THREAD

**Issue by davelab6** [adobe-type-tools/box-drawing#4]
The URL at the top of https://github.com/adobe-type-tools/box-drawing/ is still http://adobe-type-tools.github.com/boxDrawing/ but the repo was since renamed, so it should be http://adobe-type-tools.github.com/box-drawing

**Comment by frankrolf** [comment]
Thanks for the hint, but the link seems to be broken throughout, even with the proper URL. (I think it would have re-directed to the proper URL anyway).
It seems I have to re-initialize the gh-pages branch.

**Comment by davelab6** [comment]
Ah yeah when you rename its ok but if you migrate user -> org it breaks and you need to recreate the branch (pushing isn't enough)

**Comment by frankrolf** [comment]
Oh, Git.
Thanks. It’s fixed now.
